name: baseline+smart_init
model: facebook/bart-large

penman_linearization: True
use_pointer_tokens: True
raw_graph: False
remove_wiki: False
dereify: False
collapse_name_ops: False
batch_size: 2048
beam_size: 1
dropout: 0.25
attention_dropout: 0.0
smart_init: True
accum_steps: 10
warmup_steps: 1
training_steps: 250000
weight_decay: 0.004
grad_norm: 2.5
scheduler: constant
learning_rate: 0.00003
max_epochs: 30
save_checkpoints: True
log_wandb: False
warm_start: True
use_recategorization: False
best_loss: False
remove_longer_than: 1024
training_form: 'HCL'
SC_steps: 1000
IC_steps: 500


# <------------------
# Data: replace DATA below with the root of your AMR 2/3 release folder
# train: ./data/amr_annotation_3.0/data/amrs/split/training/*.txt
# dev: ./data/amr_annotation_3.0/data/amrs/split/dev/*.txt
# test: ./data/amr_annotation_3.0/data/amrs/split/test/*.txt

# Data: replace DATA below with the root of your AMR 2/3 release folder
train: ./data/amr_annotation_2.0/data/amrs/split/training/*.txt
dev: ./data/amr_annotation_2.0/data/amrs/split/dev/*.txt
test: ./data/amr_annotation_2.0/data/amrs/split/test/*.txt